### ISSUE TITLE
tests after installation of spectrochempy_data 

### ISSUE THREAD

**Issue by atravert** [spectrochempy/spectrochempy#239] opened 2021-02-16 16:12 UTC
**Describe you problem**

I have installed spectrochempy_data but testing does not work. On  WIN , `preferences.datadir`  returns `OSError: symbolic link privilege not held`

 for instance:

```
C:\Miniconda3\envs\scpy-dev\python.exe "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pycharm\_jb_pytest_runner.py" --path C:/Users/traverta/Dropbox/Programmes/spectrochempy/tests/test_plotters
Testing started at 16:58 ...
Launching pytest with arguments C:/Users/traverta/Dropbox/Programmes/spectrochempy/tests/test_plotters in C:\Users\traverta\Dropbox\Programmes\spectrochempy\tests\test_plotters

SpectroChemPy's API - v.0.2.11.dev2+g6ceb47f0
Loading SpectroChemPy API: 100%|██████████| 1211/1211 [00:02<00:00, 548.16it/s]
© Copyright 2014-2021 - A.Travert & C.Fernandez @ LCS
ImportError while loading conftest 'C:\Users\traverta\Dropbox\Programmes\spectrochempy\tests\conftest.py'.
..\conftest.py:18: in <module>
    import spectrochempy
..\..\spectrochempy\__init__.py:74: in <module>
    from spectrochempy import api
..\..\spectrochempy\api.py:126: in <module>
    DATADIR = pathclean(preferences.datadir)
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:575: in __get__
    return self.get(obj, cls)
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:538: in get
    default = obj.trait_defaults(self.name)
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:1578: in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:975: in __call__
    return self.func(*args, **kwargs)
..\..\spectrochempy\application.py:478: in _get_default_datadir
    return self.parent.datadir.path
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:575: in __get__
    return self.get(obj, cls)
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:538: in get
    default = obj.trait_defaults(self.name)
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:1578: in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:975: in __call__
    return self.func(*args, **kwargs)
..\..\spectrochempy\application.py:418: in _get_path_default
    path.symlink_to(testdata, target_is_directory=True)
C:\Miniconda3\envs\scpy-dev\lib\pathlib.py:1352: in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
E   OSError: symbolic link privilege not held

Process finished with exit code 4
```

**Comment by atravert** [comment] 2021-02-16 16:14
I have seen a similar problem here:

https://github.com/explosion/spaCy/issues/895#issuecomment-289198926

**Comment by fernandezc** [comment] 2021-02-16 16:21
Arnaud Can you check if you have a testdata directory (normally a symlink) in   $HOME/.spectrochempy   (spectrochempy with a starting dot) 

Anyway I think it should work without this but I will check again.

**Comment by fernandezc** [comment] 2021-02-16 16:29
This link should point on the actual data: in   <your_env>/share/spectrochempy_data/testdata

(Use` where python `. to now the path to your env. For me it is: /Users/christian/opt/miniconda3/envs/scpy_dev
so I can check the presence of th files:
```
ls /Users/christian/opt/miniconda3/envs/scpy_dev/share/spectrochempy_data/tesdata
```

**Comment by fernandezc** [comment] 2021-02-16 16:40
I think it is a problem with the installation of the symlink on windows. But I thought I had made a work around on this. I'll check again.

**Comment by atravert** [comment] 2021-02-16 16:41
It seems that the symlink is created only when spectrochempy_data is installed with admin privileges. But then the link is in my admin home/.spectrochempy  dir,  not my user directory.   

I will fix it manually on my system.

**Comment by fernandezc** [comment] 2021-02-16 16:45
Indeed, you can you create the link yourself for the moment. May be the simpler to solve this problem( I already spend to much time) on this would be to modified the setup.py to install the data in the .spectrochempy dir.  This is what I do in Colab, if you look at the documentation. This is probably the simpler (or may be setup.py could create this link). I will look at this.

**Comment by fernandezc** [comment] 2021-02-16 17:16
There is something quite strange:

I don't see why it the symlink is not installed you have this error:
```
    import spectrochempy
..\..\spectrochempy\__init__.py:74: in <module>
    from spectrochempy import api
..\..\spectrochempy\api.py:126: in <module>
    DATADIR = pathclean(preferences.datadir)         
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:575: in __get__
    return self.get(obj, cls)
C:\Miniconda3\envs\scpy-dev\lib\site-packages\traitlets\traitlets.py:538: in get
    default = obj.trait_defaults(self.name)
```

``DATADIR = pathclean(preferences.datadir)``   do not try to find the file: it just set a path. 

on my Mac, if I remove the symlink from .spectrochempy: 
I got the error when try to read file, because of course they are not present.

```
Loading SpectroChemPy API: 100%|██████████| 1211/1211 [00:01<00:00, 820.53it/s]
 WARNING | No file with name `/Users/christian/.spectrochempy/testdata/irdata/nh4y-activation.spg` could be found. Sorry!
ERROR: file or directory no found....
```

**Comment by fernandezc** [comment] 2021-02-16 17:23
OK I see the problem is here;
418 in application.py 
```path.symlink_to(testdata, target_is_directory=True)```

**Comment by atravert** [comment] 2021-02-16 17:23
I confirm: if the symlink is not present (or renamed) I have this error `OSError: symbolic link privilege not held`

**Comment by fernandezc** [comment] 2021-02-16 17:24
Actually The symlink should be created with this instruction, but it doesn't work.

**Comment by atravert** [comment] 2021-02-16 17:29
The reason is probably here: https://security.stackexchange.com/questions/10194/why-do-you-have-to-be-an-admin-to-create-a-symlink-in-windows

(the kids are back, I am leaving for some time from now ... :-).

**Comment by fernandezc** [comment] 2021-02-16 19:56
For the moment I tried to solve the problem by just copying files instead of doing a symlink . I am not sure this is the best solution, I will think about another way to install directly in this folder. For this I need to modify spectrochempy_data installation.
So for the moment, the pull request that I will merge is just a workaround

**Comment by fernandezc** [comment] 2021-02-16 20:15
Let me know if it works for you, and we close this issue. I should also tag it as soon it is ok, so that the windows users can load a working version.

**Comment by atravert** [comment] 2021-02-16 22:17
It is working  but it seems that data files are duplicated in the .spectrochempy folder: I have all the subfolders that were in testdata + testdata and the same subfolders, i.e. 
```
.spectrochempy/
    |- agirdata/
    |- irdata/
    |- matladata/
   (....)
    |- testdata/
        |- agirdata/
        |- irdata/
        |- matlabdata/
       (...)
        |- wodger.spg
   |- wodger.spg
```
I can't check but I suspect I had also something like that with the symlink)

**Comment by fernandezc** [comment] 2021-02-17 08:54
yes, there is still some problems. I am right now trying to install directly the spectrochempy_data in the .spectrochempy/testdata directory, so there will be no needs anymore to symlink or to copy data.

**Closed** 2021-02-17 17:46 UTC
Labels: help wanted
