### ISSUE TITLE
read_dir() and other read_*() methods do not return error when non-existing directory

### ISSUE THREAD

**Issue by Aboulaytreda** [spectrochempy/spectrochempy#197] opened 2021-01-29 15:39 UTC
**Describe the bug**
calling `read_dir()` with a wrong directory name returns nothing

**To Reproduce**
X = read_dir("a_fake_name")
print(X)
**Expected behavior**
An error message should indicate the non existence of the directory

**Desktop (please complete the following information):**
 - OS: win10
 - Python version: 3.7)
 - SpectroChemPy version : 0.2.4

**Comment by fernandezc** [comment] 2021-01-29 15:47
I can't reproduce this in Jupiter lab. 
I get   ERROR  Not implementError 
The message is not clear indeed, but there is one.

**Comment by fernandezc** [comment] 2021-01-29 15:49
Can you upgrade two the 0.2.5 version and try again?   please

**Comment by fernandezc** [comment] 2021-01-29 15:54
<img width="828" alt="image" src="https://user-images.githubusercontent.com/2428474/106296988-944f5700-6252-11eb-83fc-2fffba3c0a6e.png">

**Comment by atravert** [comment] 2021-01-29 16:00
OK. Ipython also returns 'ERROR Not Implemented'

Reda uses Spyder. I will check on my side if I can reproduce it.

for read omnic the minor issue was when calling `scp.read_omnic(directory="fake_directory")` : in such a case an 'open directory' dialog box was opened, whil one would expect an error ?  (but this second case is a minor issue)

**Comment by fernandezc** [comment] 2021-01-29 16:05
well... regarding the behaviour, there is indeed some changes compare to the version 0.1.x

basically all reading function (and read_dir is now almost equivalent to read) can be described as here:
https://www.spectrochempy.fr/latest/userguide/reference/generated/spectrochempy.read.html#spectrochempy.read

**Comment by fernandezc** [comment] 2021-01-29 16:06
Look it and tell me if really you think some behaviour should be different. 

All function read_x.  can be actually replaced by read if you pride a protocol or an extension to the file.

**Comment by fernandezc** [comment] 2021-01-29 16:28
One think I just notice is that function that open a dialog:

scp.read(directory='irdata/OPUS', merge=True).   for example

give a system error in a terminal (this is may be the case of Spyder). Using GUI such as TK is the probably the problem. I need to search if some setting can solve this.

**Comment by fernandezc** [comment] 2021-01-29 16:30
May be this capability should be deactivated when we are not in jupyter lab?

**Comment by atravert** [comment] 2021-01-29 16:39
On WIN, the command

scp.read(directory='irdata/OPUS', merge=True)

works in ipython terminal. The dialog box also popped up using spyder. 
The small issue was that it popped up even when a wrong directory was 
used (in the user default directory I guess. On win: 
C:\users\<user>\Documents).  But this could be an expected behaviour as 
well :-)


Le 29/01/2021 à 17:31, Christian Fernandez a écrit :

**Comment by fernandezc** [comment] 2021-01-29 16:54
> But this could be an expected behaviour as well :-)

I think so... it give you a chance to open a correct file instead of giving an error... but I agree this can be discussed, although it is a minor problem. 

I am happy that dialog runs on windows:  Not the case with OS X.

**Comment by fernandezc** [comment] 2021-01-29 16:58
Actually I don't like very mush having the dialog, which do not make real sense when you write scripts. If it is not a scripts, then Jupiter Lab and the "fileselector" widgets is a good choice that I would recommend: https://www.spectrochempy.fr/latest/userguide/importexport/import.html#File-selector-widget

**Comment by fernandezc** [comment] 2021-02-25 18:25
@atravert is there still problem with this issue, or should we close it?

**Comment by atravert** [comment] 2021-02-25 22:45
it is solved now :-), we can close it

Le 25/02/2021 à 19:25, Christian Fernandez a écrit :

**Closed** 2021-02-26 00:25 UTC
Labels: bug
